Repository garageScript/myProxy, pull requests merged in 2019-10, with the labels that each got.

#252 Quick fix
  docs/index.md
  src/api/admin.ts
  src/auth/index.ts
  src/helpers/domainSetup.ts
  src/server/server.ts
  src/tests/integration/mapping.test.ts
Labels: Bug 🐛

#245 Integration test for api/availableDomains
  src/tests/api.test.ts
Labels: Test 🧪

#246 Integration test: Delete mapping
  src/api/mapping.ts
  src/tests/helpers/mappingAdapter.ts
  src/tests/integration/mapping.test.ts
  src/types/tests.ts
Labels: Test 🧪

#255 close #241 CSS buttons should match/Update comment
  src/public/client.ts
  src/public/providers.ts
  views/client.ejs
Labels: Easy To Reviewed ✅

#256 Fix /api/mappings/download endpoint
  src/api/mapping.ts
Labels: Bug 🐛

#260 Fixes Duplicate Subdomain Test/Avoids Dummy data in DB
  src/tests/integration/mapping.test.ts
Labels: Test 🧪

#257 Fix test api/availableDomains
  src/tests/api.test.ts
Labels: Bug 🐛, Test 🧪

#259 Test Fix: Deletes Mapping after creation/Avoid dummy data in DB
  src/tests/integration/mapping.test.ts
Labels: Test 🧪

#270 Fix prettier check
  package.json
  src/api/mapping.ts
Labels: Easy To Reviewed ✅

#268 Fix Invalid requests causes server to crash
  src/app.ts
  src/helpers/SNICallback.ts
  src/server/server.ts
Labels: Bug 🐛

#273 Fix startProxyServer
  src/server/server.ts
Labels: Bug 🐛
