Repository garageScript/myProxy, pull requests merged in 2019-09, with the labels that each got.

#51 [Tech Debt] Refactor - fetch
  src/helpers/httpRequest.ts
  src/providers/goDaddy.ts
Labels: Easy To Reviewed ✅

#50 Update README.md
  README.md
Labels: Easy To Reviewed ✅

#57 Clean up
  src/app.ts
Labels: Easy To Reviewed ✅

#67 Fix undefined name
  src/providers/goDaddy.ts
Labels: Easy To Reviewed ✅

#96 Overview Part 1 .3
  src/api/admin.ts
  src/api/types/general.ts
  src/app.ts
  src/providers/goDaddy.ts
  src/providers/index.ts
  src/public/client.ts
Labels: API 🤖

#104 Bug: SSL Cert needs to send two commands for *.domain and .domain
  src/api/admin.ts
Labels: Bug 🐛

#111 update README
  README.md
Labels: Documentation 📚, Easy To Reviewed ✅

#113 Fix bug #112
  scripts/setup.sh
Labels: Bug 🐛, Easy To Reviewed ✅

#118 Add auth middleware
  src/admin/index.ts
  src/api/index.ts
  src/app.ts
  src/auth/index.ts
Labels: Admin 🔑, Bug 🐛, MainApp

#125 Move password check to auth file
  src/app.ts
  src/auth/index.ts
Labels: Admin 🔑, Easy To Reviewed ✅, refactor

#127 Removed Eslint rule for any and camel case
  .eslintrc.json
  src/api/lib/data.ts
  src/api/serviceConfig.ts
  src/api/types/general.ts
  src/providers/goDaddy.ts
  src/providers/index.ts
  src/public/client.ts
  src/public/providers.ts
  tsconfig.json
Labels: Easy To Reviewed ✅

#126 Auto redirect to admin page if there are no availableDomains
  src/app.ts
Labels: Admin 🔑, Easy To Reviewed ✅

#140 Bug fix
  src/app.ts
Labels: Bug 🐛, Easy To Reviewed ✅

#138 ⚠️ Issue 129 Please do not merge before test it
  src/api/admin.ts
  src/api/mapping.ts
  src/app.ts
  src/lib/data.ts
  src/providers/goDaddy.ts
  src/providers/index.ts
  src/types/admin.ts
  src/types/general.ts
Labels: MainApp, refactor

#145 Store HashPassword in Local
  src/app.ts
  src/auth/index.ts
  src/helpers/crypto.ts
Labels: MainApp

#143 Fix api/admin/availableDomains to api/availableDomains
  src/api/admin.ts
  src/api/index.ts
Labels: API 🤖, Easy To Reviewed ✅

#139 Add script command `npm run server`
  .eslintrc.json
  package.json
  scripts/deploy.sh
  scripts/prod.config.js
  scripts/setup.sh
Labels: MainApp

#144 Fetch Dropdown
  src/public/client.ts
Labels: MainApp

#160 Update command `npm run server`
  package.json
Labels: Easy To Reviewed ✅

#164 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation 📚

#163 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Documentation 📚

#194 Creates git repository for git user
  src/api/mapping.ts
Labels: Easy To Reviewed ✅

#211 add dropdown + autofix
  package-lock.json
  src/api/mapping.ts
  src/public/client.ts
  src/public/providers.ts
  views/client.ejs
Labels: UI 💅

#216 Bug fix - port in deploy.config was null
  src/api/mapping.ts
Labels: Easy To Reviewed ✅

#218 Bug Fix - Adds correct pm2 flags and npm install
  scripts/post-receive
Labels: Easy To Reviewed ✅

#219 Polish UI for key Input
  src/public/providers.ts
Labels: UI 💅

#220 Polish UI and fix Html semantic Domain list
  src/public/providers.ts
Labels: UI 💅

#223 Bug Fix - GoDaddy key inputs were null
  src/public/providers.ts
Labels: Easy To Reviewed ✅

#221 Add Message when domain is loading to setup
  src/public/providers.ts
Labels: UI 💅

#222 Polish Client page and fix html semantic
  src/public/client.ts
  src/server/server.ts
  views/client.ejs
Labels: UI 💅

#235 CSS Login Page
  views/client.ejs
  views/login.ejs
Labels: Easy To Reviewed ✅, UI 💅
